package handler

import (
	"context"
	"crypto/rand"
	"fmt"
	"math/big"
	"time"

	"github.com/gitopia/gitopia-mcp-server/internal/gitopia"
	"github.com/gitopia/gitopia-mcp-server/internal/logging"
	"github.com/gitopia/gitopia-mcp-server/internal/session"
	"github.com/gitopia/gitopia-mcp-server/internal/signing"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// GetUserContext returns the current user context information
func (h *ToolHandler) GetUserContext(
	ctx context.Context,
	req *mcp.CallToolRequest,
	_ struct{},
) (*mcp.CallToolResult, any, error) {
	contextMgr := h.getSessionContext(req)

	// Initialize context from wallet if not already done
	if !contextMgr.IsInitialized() {
		wallet, err := gitopia.WalletFromHeaders(req.Session, h.GClient)
		if err != nil {
			return toolErrorf(ErrAuthFailed, "Failed to get wallet: %s. Ensure GITOPIA_MNEMONIC is set.", err)
		}

		// Check if wallet was auto-generated (first-use)
		autoGen := false
		if ag, ok := wallet.(signing.AutoGeneratedWallet); ok {
			autoGen = ag.IsAutoGenerated()
		}

		if err := contextMgr.InitializeFromWallet(wallet.Address()); err != nil {
			// For new wallets (auto-generated or never transacted) the on-chain user
			// won't exist yet. Set a minimal context with just the address.
			contextMgr.SetContext(&session.UserContext{
				Address: wallet.Address(),
			})
		}

		if autoGen {
			// Claim fee grant for newly auto-generated wallet
			fgStatus := signing.ClaimFeeGrant(ctx, wallet.Address(), "")
			fgLine := "Fee Grant: Claimed"
			if !fgStatus.Claimed {
				fgLine = fmt.Sprintf("Fee Grant: Failed (%s)", fgStatus.Error)
			}

			// Enable fee granter on wallet so subsequent txs use the grant
			if fgStatus.Claimed {
				if fgs, ok := wallet.(signing.FeeGrantSetter); ok {
					fgs.SetFeeGranter(signing.DefaultFeeGranter())
				}
			}

			// Auto-create on-chain user
			username := randomUsername()
			userLine := fmt.Sprintf("User: %s (created)", username)
			start := time.Now()
			_, err := h.GClient.CreateUser(ctx, wallet, username)
			AuditLog("create_user", wallet.Address(), err == nil, time.Since(start), "")
			if err != nil {
				userLine = fmt.Sprintf("User: not created (%s)", err)
				logging.Warnf("Auto-create user failed: %v", err)
			} else {
				// Re-initialize context now that user exists on-chain
				_ = contextMgr.InitializeFromWallet(wallet.Address())
			}

			return toolSuccess("New wallet auto-generated", map[string]any{
				"address":   wallet.Address(),
				"username":  username,
				"fee_grant": fgLine,
				"user":      userLine,
			})
		}
	}

	uc := contextMgr.GetContext()
	if uc == nil {
		return toolSuccessData("User context", map[string]any{"initialized": false})
	}
	return toolSuccessData("User context", map[string]any{
		"address":    uc.Address,
		"username":   uc.Username,
		"active_dao": uc.ActiveDAO,
		"daos":       uc.DAOs,
	})
}

type SetActiveDAOParams struct {
	DaoName string `json:"dao_name,omitempty"` // Empty to use personal account
}

// SetActiveDAO sets the active DAO for operations
func (h *ToolHandler) SetActiveDAO(
	ctx context.Context,
	req *mcp.CallToolRequest,
	p SetActiveDAOParams,
) (*mcp.CallToolResult, any, error) {
	contextMgr := h.getSessionContext(req)

	// Initialize context from wallet if not already done
	if !contextMgr.IsInitialized() {
		wallet, err := gitopia.WalletFromHeaders(req.Session, h.GClient)
		if err != nil {
			return toolErrorf(ErrAuthFailed, "Failed to get wallet: %s. Ensure GITOPIA_MNEMONIC is set.", err)
		}

		if err := contextMgr.InitializeFromWallet(wallet.Address()); err != nil {
			return toolErrorf(ErrInternal, "Failed to initialize context: %s", err)
		}
	}

	if err := contextMgr.SetActiveDAO(p.DaoName); err != nil {
		return toolErrorf(ErrNotFound, "Failed to set active DAO: %s", err)
	}

	if p.DaoName == "" {
		return toolSuccess("Cleared active DAO, using personal account for operations", nil)
	}
	return toolSuccess(fmt.Sprintf("Set active DAO to: %s", p.DaoName), map[string]any{"dao_name": p.DaoName})
}

// RefreshUserContext refreshes the user context from Gitopia
func (h *ToolHandler) RefreshUserContext(
	ctx context.Context,
	req *mcp.CallToolRequest,
	_ struct{},
) (*mcp.CallToolResult, any, error) {
	contextMgr := h.getSessionContext(req)

	if !contextMgr.IsInitialized() {
		return toolErrorf(ErrValidation, "No context to refresh. Use get_user_context first.")
	}

	if err := contextMgr.RefreshContext(); err != nil {
		return toolErrorf(ErrInternal, "Failed to refresh context: %s", err)
	}

	return toolSuccess("Context refreshed", nil)
}

// ClaimFeeGrantParams holds parameters for the claim_fee_grant tool.
type ClaimFeeGrantParams struct {
	Address string `json:"address,omitempty" jsonschema:"If empty, uses current wallet address"`
}

// ClaimFeeGrant claims a fee grant from the Gitopia faucet.
func (h *ToolHandler) ClaimFeeGrant(
	ctx context.Context,
	req *mcp.CallToolRequest,
	p ClaimFeeGrantParams,
) (*mcp.CallToolResult, any, error) {
	address := p.Address
	if address == "" {
		wallet, err := gitopia.WalletFromHeaders(req.Session, h.GClient)
		if err != nil {
			return toolErrorf(ErrAuthFailed, "Failed to get wallet: %s", err)
		}
		address = wallet.Address()
	}

	status := signing.ClaimFeeGrant(ctx, address, "")
	if !status.Claimed {
		return toolErrorf(ErrChainTx, "Fee grant claim failed for %s: %s", address, status.Error)
	}

	return toolSuccess(fmt.Sprintf("Fee grant claimed for %s", address), map[string]any{"address": address})
}

// CreateUserParams holds parameters for the create_user tool.
type CreateUserParams struct {
	Username string `json:"username" jsonschema:"Gitopia username (3-39 chars, alphanumeric and hyphens)"`
}

// CreateUser creates an on-chain Gitopia user for the current wallet.
func (h *ToolHandler) CreateUser(
	ctx context.Context,
	req *mcp.CallToolRequest,
	p CreateUserParams,
) (*mcp.CallToolResult, any, error) {
	if h.ChainLimiter != nil {
		if err := h.ChainLimiter.Allow(); err != nil {
			return toolErrorf(ErrRateLimited, "%s", err)
		}
	}
	if h.DryRunMode {
		return DryRunResult("create_user", p)
	}

	wallet, err := gitopia.WalletFromHeaders(req.Session, h.GClient)
	if err != nil {
		return toolErrorf(ErrAuthFailed, "Failed to get wallet: %s", err)
	}

	start := time.Now()
	_, err = h.GClient.CreateUser(ctx, wallet, p.Username)
	AuditLog("create_user", wallet.Address(), err == nil, time.Since(start), "")
	if err != nil {
		return toolErrorf(ErrChainTx, "Failed to create user: %s", err)
	}

	return toolSuccess("Created user", map[string]any{
		"username": p.Username,
		"address":  wallet.Address(),
	})
}

// randomUsername generates a username like "user-a1b2c3".
func randomUsername() string {
	const chars = "abcdefghijklmnopqrstuvwxyz0123456789"
	suffix := make([]byte, 6)
	for i := range suffix {
		n, _ := rand.Int(rand.Reader, big.NewInt(int64(len(chars))))
		suffix[i] = chars[n.Int64()]
	}
	return "user-" + string(suffix)
}
