package signing

import (
	"context"
	"encoding/json"
	"fmt"
	"math/rand/v2"
	"os"
	"strconv"
	"strings"
	"time"

	"github.com/cosmos/cosmos-sdk/client/grpc/tmservice"
	clientTx "github.com/cosmos/cosmos-sdk/client/tx"
	"github.com/cosmos/cosmos-sdk/codec"
	"github.com/cosmos/cosmos-sdk/codec/types"
	"github.com/cosmos/cosmos-sdk/crypto/hd"
	cosmoscryptoed "github.com/cosmos/cosmos-sdk/crypto/keys/ed25519"
	cosmoscryptosecp "github.com/cosmos/cosmos-sdk/crypto/keys/secp256k1"
	cryptotypes "github.com/cosmos/cosmos-sdk/crypto/types"
	sdk "github.com/cosmos/cosmos-sdk/types"
	"github.com/cosmos/cosmos-sdk/types/tx"
	"github.com/cosmos/cosmos-sdk/types/tx/signing"
	xauthsigning "github.com/cosmos/cosmos-sdk/x/auth/signing"
	authtx "github.com/cosmos/cosmos-sdk/x/auth/tx"
	authtype "github.com/cosmos/cosmos-sdk/x/auth/types"
	banktypes "github.com/cosmos/cosmos-sdk/x/bank/types"
	"github.com/cosmos/cosmos-sdk/x/feegrant"
	"github.com/gitopia/gitopia-mcp-server/internal/logging"
	"github.com/gitopia/gitopia-mcp-server/internal/signing/config"
	gitopia "github.com/gitopia/gitopia/v6/app"
	offchaintypes "github.com/gitopia/gitopia/v6/x/offchain/types"
	"github.com/pkg/errors"
	"google.golang.org/grpc"
)

type Account struct {
	Address       string `json:"address"`
	PathIncrement int    `json:"pathIncrement"`
}

type GitopiaWalletFile struct {
	Name          string    `json:"name"`
	Mnemonic      string    `json:"mnemonic"`
	HDpath        string    `json:"HDpath"`
	Password      string    `json:"password"`
	Prefix        string    `json:"prefix"`
	PathIncrement int       `json:"pathIncrement"`
	Accounts      []Account `json:"accounts"`
}

type GitopiaWallet struct {
	walletFile     GitopiaWalletFile
	privateKey     cryptotypes.PrivKey
	address        string
	secType        secretType
	feeGranterAddr string
	autoGenerated  bool
}

// IsAutoGenerated returns true if this wallet was auto-generated (not from user config).
func (gw GitopiaWallet) IsAutoGenerated() bool { return gw.autoGenerated }

// SetFeeGranter sets the fee granter address so transactions use fee grants.
func (gw *GitopiaWallet) SetFeeGranter(granter string) { gw.feeGranterAddr = granter }

func InitGitopiaWallet(ctx context.Context, bankClient banktypes.QueryClient, feegrantClient feegrant.QueryClient) (Wallet, error) {
	var buffer []byte
	var err error
	gw := GitopiaWallet{}

	// Read wallet
	isGitHubAction := os.Getenv("GITHUB_ACTIONS")
	if isGitHubAction == "true" {
		// Read from GitHub secret
		buffer = []byte(os.Getenv("GITOPIA_WALLET"))
		gw.secType = GITHUB_SEC
	} else if len(os.Getenv("GITOPIA_WALLET")) != 0 {
		gitopiaWalletPath := os.Getenv("GITOPIA_WALLET")
		buffer, err = os.ReadFile(gitopiaWalletPath)
		if err != nil {
			return nil, errors.Wrap(err, "unable to read gitopia wallet")
		}
		gw.secType = ENV_VAR
	} else {
		return nil, errors.New("GITOPIA_WALLET environment variable is not set")
	}

	err = json.Unmarshal(buffer, &gw.walletFile)
	if err != nil {
		return nil, errors.Wrap(err, "error decoding wallet file")
	}

	gw.privateKey, err = gw.privKey()
	if err != nil {
		return nil, err
	}
	gw.address = sdk.AccAddress(gw.privateKey.PubKey().Address()).String()

	if bankClient != nil && feegrantClient != nil {
		b, err := bankClient.Balance(ctx, &banktypes.QueryBalanceRequest{
			Address: gw.address,
			Denom:   config.Denom,
		})
		if err != nil {
			return nil, errors.New("error querying for balance")
		}

		// Use fee grant only when balance is zero
		if b.Balance.Amount.IsZero() {
			fr, _ := feegrantClient.Allowance(ctx, &feegrant.QueryAllowanceRequest{
				Granter: config.FeeGranterAddr,
				Grantee: gw.address,
			})
			if fr == nil {
				return nil, errors.New("no feegrant available")
			}

			gw.feeGranterAddr = fr.Allowance.Granter
		}
	}

	return gw, nil
}

func (gw GitopiaWallet) SignData(data []byte) (string, error) {
	encConf := gitopia.MakeEncodingConfig()
	offchaintypes.RegisterInterfaces(encConf.InterfaceRegistry)
	offchaintypes.RegisterLegacyAminoCodec(encConf.Amino)

	signer := offchaintypes.NewSigner(encConf.TxConfig, gw.privateKey)
	accAddress, err := sdk.AccAddressFromBech32(gw.Address())
	if err != nil {
		return "", errors.Wrap(err, "invalid bech32 address")
	}
	signData := offchaintypes.NewMsgSignData(accAddress, data)

	tx, err := signer.Sign([]sdk.Msg{signData})
	if err != nil {
		return "", errors.Wrap(err, "error signing data")
	}

	txBz, err := encConf.TxConfig.TxJSONEncoder()(tx)
	if err != nil {
		return "", errors.Wrap(err, "error encoding tx")
	}

	return string(txBz), nil
}
// validateAllowedMsgs checks that every message is an allowed Gitopia or governance type.
// This prevents the wallet from signing dangerous messages (e.g. bank transfers, staking).
func validateAllowedMsgs(msgs []sdk.Msg) error {
	for _, msg := range msgs {
		typeURL := sdk.MsgTypeURL(msg)
		if strings.HasPrefix(typeURL, "/gitopia.gitopia.gitopia.") {
			continue
		}
		if strings.HasPrefix(typeURL, "/cosmos.group.v1.") {
			continue
		}
		return fmt.Errorf("message type %s is not allowed; only Gitopia and group governance messages can be signed", typeURL)
	}
	return nil
}

func (gw GitopiaWallet) SignAndBroadcast(ctx context.Context, grpcConn *grpc.ClientConn, msgs []sdk.Msg) (*tx.GetTxResponse, error) {
	if err := validateAllowedMsgs(msgs); err != nil {
		return nil, err
	}

	txClient := tx.NewServiceClient(grpcConn)
	accountQueryClient := authtype.NewQueryClient(grpcConn)
	interfaceRegistry := types.NewInterfaceRegistry()
	interfaceRegistry.RegisterInterface(
		"cosmos.auth.v1beta1.AccountI",
		(*authtype.AccountI)(nil),
		&authtype.BaseAccount{},
		&authtype.ModuleAccount{},
	)
	interfaceRegistry.RegisterInterface("cosmos.crypto.PubKey", (*cryptotypes.PubKey)(nil))
	interfaceRegistry.RegisterImplementations((*cryptotypes.PubKey)(nil), &cosmoscryptosecp.PubKey{})
	interfaceRegistry.RegisterImplementations((*cryptotypes.PubKey)(nil), &cosmoscryptoed.PubKey{})
	marshaler := codec.NewProtoCodec(interfaceRegistry)
	txCfg := authtx.NewTxConfig(marshaler, authtx.DefaultSignModes)

	txBuilder := txCfg.NewTxBuilder()
	err := txBuilder.SetMsgs(msgs...)
	if err != nil {
		return nil, err
	}

	res, err := accountQueryClient.Account(ctx,
		&authtype.QueryAccountRequest{
			Address: gw.Address(),
		},
	)
	if err != nil {
		return nil, err
	}
	var acc authtype.AccountI
	if err := interfaceRegistry.UnpackAny(res.Account, &acc); err != nil {
		return nil, err
	}

	signMode := txCfg.SignModeHandler().DefaultMode()
	sigV2 := signing.SignatureV2{
		PubKey: gw.privateKey.PubKey(),
		Data: &signing.SingleSignatureData{
			SignMode:  signMode,
			Signature: nil,
		},
		Sequence: acc.GetSequence(),
	}
	err = txBuilder.SetSignatures(sigV2)
	if err != nil {
		return nil, err
	}

	gas, err := calculateGas(ctx, grpcConn, txClient, txCfg, txBuilder)
	if err != nil {
		return nil, err
	}
	txBuilder.SetGasLimit(gas)

	fee, err := calculateFee(gas)
	if err != nil {
		return nil, err
	}
	txBuilder.SetFeeAmount(fee)

	if gw.feeGranterAddr != "" {
		feeGranterAddr, err := sdk.AccAddressFromBech32(gw.feeGranterAddr)
		if err != nil {
			return nil, err
		}
		feePayerAddr, err := sdk.AccAddressFromBech32(gw.Address())
		if err != nil {
			return nil, err
		}

		txBuilder.SetFeeGranter(feeGranterAddr)
		txBuilder.SetFeePayer(feePayerAddr)
	}

	// Get chain id for signing transaction
	serviceClient := tmservice.NewServiceClient(grpcConn)
	nodeInfoRes, err := serviceClient.GetNodeInfo(ctx, &tmservice.GetNodeInfoRequest{})
	if err != nil {
		return nil, err
	}
	chainId := nodeInfoRes.DefaultNodeInfo.Network

	signerData := xauthsigning.SignerData{
		ChainID:       chainId,
		AccountNumber: acc.GetAccountNumber(),
		Sequence:      acc.GetSequence(),
	}

	sigV2, err = clientTx.SignWithPrivKey(signMode, signerData,
		txBuilder, gw.privateKey, txCfg, acc.GetSequence())
	if err != nil {
		return nil, err
	}

	err = txBuilder.SetSignatures(sigV2)
	if err != nil {
		return nil, err
	}

	err = txBuilder.GetTx().ValidateBasic()
	if err != nil {
		return nil, errors.Wrap(err, "tx validation failed")
	}

	txBytes, err := txCfg.TxEncoder()(txBuilder.GetTx())
	if err != nil {
		return nil, err
	}

	grpcRes, err := txClient.BroadcastTx(
		ctx,
		&tx.BroadcastTxRequest{
			Mode:    tx.BroadcastMode_BROADCAST_MODE_SYNC,
			TxBytes: txBytes,
		},
	)
	if err != nil {
		return nil, err
	}

	if grpcRes.TxResponse.Code != 0 {
		return nil, fmt.Errorf("fatal: failed to broadcast transaction: %v", grpcRes.TxResponse)
	}

	// Poll for transaction confirmation with exponential backoff
	txResponse, err := gw.pollForTxConfirmationStructured(ctx, txClient, grpcRes.TxResponse.TxHash)
	if err != nil {
		return nil, err
	}

	return txResponse, nil
}
func (gw GitopiaWallet) pollForTxConfirmationStructured(ctx context.Context, txClient tx.ServiceClient, txHash string) (*tx.GetTxResponse, error) {
	const (
		maxRetries    = 20
		initialDelay  = 500 * time.Millisecond
		maxDelay      = 5 * time.Second
		timeout       = 60 * time.Second
		backoffFactor = 1.5
	)

	ctx, cancel := context.WithTimeout(ctx, timeout)
	defer cancel()

	delay := initialDelay
	logging.Infof("Starting transaction polling: hash=%s timeout=%v maxRetries=%d", txHash, timeout, maxRetries)

	for attempt := 0; attempt < maxRetries; attempt++ {
		select {
		case <-ctx.Done():
			logging.Errorf("Timeout waiting for transaction: hash=%s timeout=%v", txHash, timeout)
			return nil, fmt.Errorf("timeout waiting for transaction %s after %v", txHash, timeout)
		default:
		}

		txResponse, err := txClient.GetTx(ctx, &tx.GetTxRequest{
			Hash: txHash,
		})

		if err != nil {
			if isTxNotFoundError(err) {
				logging.Debugf("Transaction pending: hash=%s attempt=%d/%d nextRetry=%v",
					txHash, attempt+1, maxRetries, delay)
			} else {
				logging.Errorf("Query error: hash=%s error=%v", txHash, err)
				return nil, fmt.Errorf("error querying transaction %s: %w", txHash, err)
			}
		} else {
			if txResponse.TxResponse.Code != 0 {
				logging.Errorf("Transaction failed: hash=%s code=%d log=%s",
					txHash, txResponse.TxResponse.Code, txResponse.TxResponse.RawLog)
				return nil, fmt.Errorf("transaction %s failed with code %d: %s",
					txHash, txResponse.TxResponse.Code, txResponse.TxResponse.RawLog)
			}

			logging.Infof("Transaction confirmed: hash=%s attempts=%d", txHash, attempt+1)
			return txResponse, nil
		}

		// Wait before next attempt
		select {
		case <-ctx.Done():
			logging.Warnf("Context cancelled during backoff: hash=%s", txHash)
			return nil, fmt.Errorf("timeout waiting for transaction %s", txHash)
		case <-time.After(delay):
		}

		// Exponential backoff with jitter
		oldDelay := delay
		delay = time.Duration(float64(delay) * backoffFactor)
		if delay > maxDelay {
			delay = maxDelay
		}

		// Add jitter (±20% of delay)
		jitter := time.Duration(float64(delay) * 0.2 * (2*rand.Float64() - 1))
		delay += jitter

		logging.Debugf("Backoff applied: hash=%s oldDelay=%v newDelay=%v jitter=%v",
			txHash, oldDelay, delay, jitter)
	}

	logging.Errorf("Transaction not confirmed: hash=%s maxAttempts=%d", txHash, maxRetries)
	return nil, fmt.Errorf("transaction %s not confirmed after %d attempts", txHash, maxRetries)
}

// isTxNotFoundError checks if the error indicates transaction not found
func isTxNotFoundError(err error) bool {
	errStr := strings.ToLower(err.Error())
	return strings.Contains(errStr, "not found") ||
		strings.Contains(errStr, "tx not found") ||
		strings.Contains(errStr, "transaction not found") ||
		strings.Contains(errStr, "not indexed") ||
		strings.Contains(errStr, "code = notfound")
}
func (gw GitopiaWallet) Address() string {
	return gw.address
}

func (gw GitopiaWallet) Type() secretType {
	return gw.secType
}

// Export returns the wallet data in JSON format for git-remote-gitopia
func (gw GitopiaWallet) Export() ([]byte, error) {
	return json.Marshal(gw.walletFile)
}

func (gw GitopiaWallet) privKey() (cryptotypes.PrivKey, error) {
	// Generate private key
	hdPath := gw.walletFile.HDpath + strconv.Itoa(gw.walletFile.PathIncrement)
	derivedPriv, err := hd.Secp256k1.Derive()(gw.walletFile.Mnemonic, "", hdPath)
	if err != nil {
		return nil, err
	}

	privKey := hd.Secp256k1.Generate()(derivedPriv)
	return privKey, nil
}
