package signing

import (
	"context"
	"fmt"

	"strings"

	"github.com/cosmos/go-bip39"

	"github.com/cosmos/cosmos-sdk/crypto/hd"
	sdk "github.com/cosmos/cosmos-sdk/types"
	"github.com/cosmos/cosmos-sdk/types/tx"
	banktypes "github.com/cosmos/cosmos-sdk/x/bank/types"
	"github.com/cosmos/cosmos-sdk/x/feegrant"
	"google.golang.org/grpc"

	"github.com/gitopia/gitopia-mcp-server/internal/signing/config"
)

type secretType int

const (
	UNKNOWN secretType = iota
	ENV_VAR
	LEDGER
	KEYRING_BACKEND
	GITHUB_SEC
)

type Wallet interface {
	SignData(data []byte) (string, error)
	SignAndBroadcast(ctx context.Context, grpcConn *grpc.ClientConn, msgs []sdk.Msg) (*tx.GetTxResponse, error)
	Type() secretType
	Address() string
	Export() ([]byte, error) // Export wallet data for git-remote-gitopia
}

// AutoGeneratedWallet is optionally implemented by wallets that were auto-generated.
type AutoGeneratedWallet interface {
	IsAutoGenerated() bool
}

// FeeGrantSetter is optionally implemented by wallets that can have a fee granter set.
type FeeGrantSetter interface {
	SetFeeGranter(granter string)
}

// GenerateMnemonic creates a new 24-word BIP-39 mnemonic using 256-bit entropy.
func GenerateMnemonic() (string, error) {
	entropy, err := bip39.NewEntropy(256)
	if err != nil {
		return "", fmt.Errorf("failed to generate entropy: %w", err)
	}
	mnemonic, err := bip39.NewMnemonic(entropy)
	if err != nil {
		return "", fmt.Errorf("failed to generate mnemonic: %w", err)
	}
	return mnemonic, nil
}

// FromMnemonic constructs a GitopiaWallet from a raw BIP-39 mnemonic. This is a
// convenience helper so that callers (e.g. WalletFromHeaders) can build a
// signing.Wallet without needing to parse wallet files or keyrings.
//
// It derives the first Cosmos HD path (m/44'/118'/0'/0/0) using Secp256k1.
// NOTE: This should be used only in trusted environments, as the mnemonic is
// handled in-memory.
func FromMnemonic(mnemonic string) (Wallet, error) {
	mnemonic = strings.TrimSpace(mnemonic)
	if len(mnemonic) < 32 {
		return nil, fmt.Errorf("mnemonic too short")
	}
	if mnemonic == "" {
		return nil, fmt.Errorf("empty mnemonic")
	}

	// Standard Cosmos HD derivation path
	hdPath := hd.CreateHDPath(118, 0, 0).String()

	derivedPriv, err := hd.Secp256k1.Derive()(mnemonic, "", hdPath)
	if err != nil {
		return nil, err
	}
	privKey := hd.Secp256k1.Generate()(derivedPriv)

	addr := sdk.AccAddress(privKey.PubKey().Address()).String()
	// Use parent HD path (without address index) — git-remote-gitopia expects
	// the parent path with the index in accounts[].pathIncrement.
	parentHDPath := "m/44'/118'/0'/0/"

	gw := &GitopiaWallet{
		privateKey: privKey,
		address:    addr,
		secType:    ENV_VAR,
		walletFile: GitopiaWalletFile{
			Name:     "mcp-wallet",
			Mnemonic: mnemonic,
			HDpath:   parentHDPath,
			Accounts: []Account{
				{Address: addr, PathIncrement: 0},
			},
		},
	}
	return gw, nil
}

// FromMnemonicWithFeegrant constructs a GitopiaWallet from a mnemonic and sets feegrant if available.
func FromMnemonicWithFeegrant(ctx context.Context, mnemonic string, bankClient banktypes.QueryClient, feegrantClient feegrant.QueryClient) (Wallet, error) {
	mnemonic = strings.TrimSpace(mnemonic)
	if len(mnemonic) < 32 {
		return nil, fmt.Errorf("mnemonic too short")
	}
	if mnemonic == "" {
		return nil, fmt.Errorf("empty mnemonic")
	}

	// Standard Cosmos HD derivation path
	hdPath := hd.CreateHDPath(118, 0, 0).String()

	derivedPriv, err := hd.Secp256k1.Derive()(mnemonic, "", hdPath)
	if err != nil {
		return nil, err
	}
	privKey := hd.Secp256k1.Generate()(derivedPriv)

	addr := sdk.AccAddress(privKey.PubKey().Address()).String()
	// Use parent HD path (without address index) — git-remote-gitopia expects
	// the parent path with the index in accounts[].pathIncrement.
	parentHDPath := "m/44'/118'/0'/0/"

	gw := &GitopiaWallet{
		privateKey: privKey,
		address:    addr,
		secType:    ENV_VAR,
		walletFile: GitopiaWalletFile{
			Name:     "mcp-wallet",
			Mnemonic: mnemonic,
			HDpath:   parentHDPath,
			Accounts: []Account{
				{Address: addr, PathIncrement: 0},
			},
		},
	}

	if bankClient != nil && feegrantClient != nil {
		b, err := bankClient.Balance(ctx, &banktypes.QueryBalanceRequest{
			Address: gw.address,
			Denom:   config.Denom,
		})
		if err != nil {
			return nil, fmt.Errorf("error querying for balance: %w", err)
		}
		if b.Balance.Amount.IsZero() {
			fr, _ := feegrantClient.Allowance(ctx, &feegrant.QueryAllowanceRequest{
				Granter: config.FeeGranterAddr,
				Grantee: gw.address,
			})
			if fr != nil && fr.Allowance != nil {
				gw.feeGranterAddr = fr.Allowance.Granter
			}
		}
	}
	return gw, nil
}

// TODO: make options optional
// func InitWallet(bankClient banktypes.QueryClient, feegrantClient feegrant.QueryClient) (Wallet, error) {
// 	wallet, err := InitOSKeyringWallet(bankClient, feegrantClient)
// 	if errors.Is(err, ErrGitopiaKeyNotConfigured) {
// 		wallet, err = InitGitopiaWallet(bankClient, feegrantClient)
// 		if err != nil {
// 			wallet, err = InitLedgerWallet(bankClient, feegrantClient)
// 			if err != nil {
// 				return nil, fmt.Errorf("fatal: Gitopia wallet is not configured! Set gitopia key or use Ledger")
// 			}
// 		}
// 	} else if err != nil {
// 		return nil, fmt.Errorf("fatal: Cannot access the gitopia key from the OS keyring, %s", err.Error())
// 	}

// 	return wallet, nil
// }
