package constants

import (
    "path/filepath"
    "strings"
)

// Path constants for MCP Gitopia server
const (
	// MCPRootDir is the root directory name for MCP data
	MCPRootDir = ".mcp"
	
	// GitopiaDir is the Gitopia-specific subdirectory under MCP root
	GitopiaDir = "gitopia"
	
	// WorkspaceSubdir is the workspace subdirectory name
	WorkspaceSubdir = "workspace"
	
	// ConfigSubdir is the config subdirectory name
	ConfigSubdir = "config"
	
	// CacheSubdir is the cache subdirectory name
	CacheSubdir = "cache"
	
	// LogsSubdir is the logs subdirectory name
	LogsSubdir = "logs"
	
	// ConfigFileName is the default config file name
	ConfigFileName = "config.json"
)

// GetMCPGitopiaPath returns the standard MCP Gitopia path: .mcp/gitopia
func GetMCPGitopiaPath() string {
	return filepath.Join(MCPRootDir, GitopiaDir)
}

// GetMCPGitopiaWorkspacePath returns the standard workspace path: .mcp/gitopia/workspace
func GetMCPGitopiaWorkspacePath() string {
	return filepath.Join(MCPRootDir, GitopiaDir, WorkspaceSubdir)
}

// GetMCPGitopiaConfigPath returns the standard config path: .mcp/gitopia/config
func GetMCPGitopiaConfigPath() string {
	return filepath.Join(MCPRootDir, GitopiaDir, ConfigSubdir)
}

// GetMCPGitopiaCachePath returns the standard cache path: .mcp/gitopia/cache
func GetMCPGitopiaCachePath() string {
	return filepath.Join(MCPRootDir, GitopiaDir, CacheSubdir)
}

// GetMCPGitopiaLogsPath returns the standard logs path: .mcp/gitopia/logs
func GetMCPGitopiaLogsPath() string {
	return filepath.Join(MCPRootDir, GitopiaDir, LogsSubdir)
}

// GitignoreTemplates provides language-specific .gitignore templates.
// Keys are case-insensitive. "generic" is the default fallback.
var GitignoreTemplates = map[string]string{
    "generic": `# Logs
logs
*.log

# OS files
.DS_Store
Thumbs.db

# IDE/editor
.vscode/
.idea/
*.swp
*.swo
*~

# Environment
.env

# Build artifacts
dist/
build/
bin/
`,

    "node": `# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage/

# nyc test coverage
.nyc_output

# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# node_modules/
node_modules/

# Optional npm cache directory
.npm

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variables file
.env

# next.js build output
.next

# IDE files
.vscode/
.idea/
*.swp
*.swo
*~

# OS generated files
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Thumbs.db
`,

    "go": `# Binaries for programs and plugins
*.exe
*.dll
*.so
*.dylib

# Test binary, built with ` + "`go test -c`" + `
*.test

# Output of the go coverage tool
*.out

# Build directories
bin/
dist/

# IDE/editor
.vscode/
.idea/

# OS
.DS_Store
Thumbs.db
`,

    "python": `# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
*$py.class

# C extensions
*.so

# Distribution / packaging
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
*.egg-info/
.installed.cfg
*.egg

# Virtual environments
env/
venv/
.venv/

# Unit test / coverage reports
.coverage
.cache
.pytest_cache/
.mypy_cache/
.tox/

# Jupyter Notebook
.ipynb_checkpoints

# IDE/editor and OS
.vscode/
.idea/
.DS_Store
Thumbs.db
.env
`,

    "rust": `# Rust
target/

# IDE/editor and OS
.vscode/
.idea/
.DS_Store
Thumbs.db
`,

    "java": `# Compiled class file
*.class

# Log file
*.log

# BlueJ files
*.ctxt

# Mobile Tools for Java (J2ME)
.mtj.tmp/

# Package Files
*.jar
*.war
*.nar
*.ear
*.zip
*.tar.gz
*.rar

# Build directories
target/
build/

# IDE/editor and OS
.classpath
.project
.settings/
.vscode/
.idea/
.DS_Store
Thumbs.db
`,

    ".net": `# Visual Studio
.vs/
bin/
obj/
*.user
*.suo
*.userosscache
*.sln.docstates

# Rider
.idea/

# OS/Editor
.vscode/
.DS_Store
Thumbs.db
`,
}

// GetGitignoreTemplate returns a .gitignore template by name (case-insensitive).
// If name is empty or unknown, returns the generic template.
func GetGitignoreTemplate(name string) string {
    key := strings.ToLower(strings.TrimSpace(name))
    if key == "" {
        key = "generic"
    }
    if tpl, ok := GitignoreTemplates[key]; ok {
        return tpl
    }
    return GitignoreTemplates["generic"]
}
